# use u and v to code the emulator and make a loss function based on LE in the next time step?
# probably more natural to use xarray instead of h5py in order (at least) to read the data...
# should be nice to extract inner + outter step functions into one so that it can be used here
# and then there is maybe going to be some forcing
# in the online step one would call the entire run_simulation function...
